name: CI

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [develop]

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
